version: "3.9"
networks:
  myNetwork:
    driver: bridge
services:
  add:
    build:
      context: ./worker
      dockerfile: ./Dockerfile
    environment:
      ADD: "true"
    networks:
      - "myNetwork"
  mult:
    build:
      context: ./worker
      dockerfile: ./Dockerfile
    environment:
      MULT: "true"
    networks:
      - "myNetwork"
  planner:
    build:
      context: ./planner
      dockerfile: ./Dockerfile
    depends_on:
      - "add"
      - "mult"
    environment:
      TASKS: "4"
      ADD: "http://add:3000"
      MULT: "http://mult:3001"
    networks:
      - "myNetwork"